### ISSUE TITLE
ProGuard Obfuscation Bug

### ISSUE THREAD

**Issue by dulleh** [dulleh/akhyou#2]
Can't run an obfuscated build due to this (retraced) error:  

```
    Process: dulleh.akhyou, PID: 12543
    java.lang.NoSuchFieldError
            at libcore.reflect.AnnotationAccess.decodeValue(AnnotationAccess.java:688)
            at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:663)
            at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:641)
            at libcore.reflect.AnnotationAccess.getDeclaredAnnotation(AnnotationAccess.java:170)
            at libcore.reflect.AnnotationAccess.getAnnotation(AnnotationAccess.java:72)
            at java.lang.Class.getAnnotation(Class.java:344)
            at com.a.a.c.f.an.<clinit>(SourceFile:170)
            at com.a.a.c.f.an.a(SourceFile:178)
            at com.a.a.c.aa.<clinit>(SourceFile:261)
            at dulleh.akhyou.d.b.d(SourceFile:110)
            at dulleh.akhyou.g.b(SourceFile:95)
            at dulleh.akhyou.MainActivity.q(SourceFile:297)
            at dulleh.akhyou.MainActivity.onCreate(SourceFile:78)
            at android.app.Activity.performCreate(Activity.java:5990)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: java.lang.NoSuchFieldException: PUBLIC_ONLY
            at java.lang.Class.getDeclaredField(Class.java:890)
            at libcore.reflect.AnnotationAccess.decodeValue(AnnotationAccess.java:685)
            at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:663)
            at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:641)
            at libcore.reflect.AnnotationAccess.getDeclaredAnnotation(AnnotationAccess.java:170)
            at libcore.reflect.AnnotationAccess.getAnnotation(AnnotationAccess.java:72)
            at java.lang.Class.getAnnotation(Class.java:344)
            at com.a.a.c.f.an.<clinit>(SourceFile:170)
            at com.a.a.c.f.an.a(SourceFile:178)
            at com.a.a.c.aa.<clinit>(SourceFile:261)
            at dulleh.akhyou.d.b.d(SourceFile:110)
            at dulleh.akhyou.g.b(SourceFile:95)
            at dulleh.akhyou.MainActivity.q(SourceFile:297)
            at dulleh.akhyou.MainActivity.onCreate(SourceFile:78)
            at android.app.Activity.performCreate(Activity.java:5990)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

This isn't too big a problem - as not obfuscating makes the apk only 0.2mb larger - but if it can be fixed, and obfuscation reenabled, that would obviously be desirable.  
  
[Here's the mapping.](https://gist.github.com/dulleh/8ffd1c3f72301d214e61)

**Comment by dulleh** [comment]
and now proguard is disabled completely! dd4284f4f5afe2563d2ffddf4af96e23e0a1d887
