### ISSUE TITLE
Failure to download when app comes to foreground

### ISSUE THREAD

**Issue by brarcher** [dulleh/akhyou#66]
This was observed on Akhyou v2.0.6 from F-Droid running on a Nexus 5 using Android 6.0.1 (CyanogenMod 13.0-20160820).

The application was opened and was navigated to an Anime's listing. The listing showed several available episodes. The application was then removed from the foreground by going home. Some time later the application was brought back to the foreground and one of the episodes selected. When this occurred a failure was reported. The following is the stack trace mentioned in the logs at the time:

```
W/System.err(15417): java.lang.NullPointerException: Attempt to invoke interface method 'java.util.List dulleh.akhyou.Models.AnimeProviders.AnimeProvider.fetchSources(java.lang.String)' on a null object reference
W/System.err(15417):    at dulleh.akhyou.Anime.AnimePresenter$3.call(SourceFile:302)
W/System.err(15417):    at dulleh.akhyou.Anime.AnimePresenter$3.call(SourceFile:300)
W/System.err(15417):    at rx.internal.operators.OnSubscribeDefer.call(Unknown)
W/System.err(15417):    at rx.internal.operators.OnSubscribeDefer.call(Unknown)
W/System.err(15417):    at rx.Observable.unsafeSubscribe(Unknown)
W/System.err(15417):    at rx.internal.operators.OperatorSubscribeOn$1$1.call(Unknown)
W/System.err(15417):    at rx.internal.schedulers.ScheduledAction.run(Unknown)
W/System.err(15417):    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
W/System.err(15417):    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err(15417):    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
W/System.err(15417):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
W/System.err(15417):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
W/System.err(15417):    at java.lang.Thread.run(Thread.java:818)
```

Closing the application by removing it from the backstack and relaunching the application gets it back into a sane state.

**Comment by dulleh** [comment]
I don't think this has anything to do with downloads, the state preservation is just a bit broken atm.
