### ISSUE TITLE
Unable to isolate JW player for AnimeBam

### ISSUE THREAD

**Issue by brarcher** [dulleh/akhyou#70]
It would seem that _Akhyou!_ v2.0.6 is no longer able to isolate the JM player div on AnimeBam, as attempting to download something from that source results in the following:
```
W/System.err(31248): java.lang.NullPointerException: Attempt to invoke virtual method 'org.jsoup.nodes.Element org.jsoup.nodes.Element.nextElementSibling()' on a null object reference
W/System.err(31248): 	at dulleh.akhyou.Utils.GeneralUtils.jwPlayerIsolate(SourceFile:97)
W/System.err(31248): 	at dulleh.akhyou.Models.SourceProviders.AnimeBamSourceProvider.fetchSource(SourceFile:19)
W/System.err(31248): 	at dulleh.akhyou.Models.AnimeProviders.BamAnimeProvider.fetchVideo(SourceFile:60)
W/System.err(31248): 	at dulleh.akhyou.Anime.AnimePresenter$5.call(SourceFile:345)
W/System.err(31248): 	at dulleh.akhyou.Anime.AnimePresenter$5.call(SourceFile:343)
W/System.err(31248): 	at rx.internal.operators.OnSubscribeDefer.call(Unknown)
W/System.err(31248): 	at rx.internal.operators.OnSubscribeDefer.call(Unknown)
W/System.err(31248): 	at rx.Observable.unsafeSubscribe(Unknown)
W/System.err(31248): 	at rx.internal.operators.OperatorSubscribeOn$1$1.call(Unknown)
W/System.err(31248): 	at rx.internal.schedulers.ScheduledAction.run(Unknown)
W/System.err(31248): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
W/System.err(31248): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err(31248): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
W/System.err(31248): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
W/System.err(31248): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
W/System.err(31248): 	at java.lang.Thread.run(Thread.java:818)
```
This seemed to work in the past, so the AnimeBam website may have updated, breaking _Akhyou!_.

**Comment by dulleh** [comment]
JWPlayer itslef has updated to a point that I don't know how to scrape it anymore. This affects a lot of providers, see 1b57546705e722dc47d5dcefe6744683e3499bf5

**Comment by dulleh** [comment]
I was able to fix for MP4Upload's use of JWPlayer but AnimeBam and YourUpload use a newer version.
